version: '3'

services:
  mysql:
    image: mysql:5.6
    container_name : library
    volumes:
       - "/var/lib/mysql56-data:/var/lib/mysql"
    environment:
        MYSQL_ROOT_PASSWORD: test
        MYSQL_DATABASE: test
    ports:
       - "3306:3306"